services:
  - type: web
    name: black-mark-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://dbadmin:<db_password>@blebleble.mssukx5.mongodb.net/black-mark-app?retryWrites=true&w=majority&appName=blebleble
      - key: TELEGRAM_BOT_TOKEN
        value: 7764525765:AAGUZJcGHmjum7YRTJ9RjZonEomACkTlpoU
      - key: PORT
        value: 10000 